### ISSUE TITLE
Prevent nodes from overlapping

### ISSUE THREAD

**Issue by Piedone** [madushans/DependenSee#1]
First of all, great project, thank you!

One small nitpick: Would you be able to modify the graph layout algorithm to don't make nodes overlap? In a large project with lot of dependencies there's a bit of manual shifting around needed to see the information.

For example, [this solution](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions) will show this graph by default:
![image](https://user-images.githubusercontent.com/1976647/105761841-e68f3000-5f53-11eb-8c7b-072e35759136.png)

You have to pan the nodes around to make it more legible:
![image](https://user-images.githubusercontent.com/1976647/105761959-0d4d6680-5f54-11eb-8743-7b1f428cf3bf.png)

**Comment by madushans** [comment]
I updated the package to enable physics animations at the start.

This should work for most cases to spread the nodes in the first few seconds of loading. It doesn't result in the same graph on multiple runs as the graphing library appears to randomly pick what to put in the middle. So you'll still have to drag things around to make sense of the dependencies.

Also unfortunately the physics system doesn't completely turn off after, so things may move around at times as you drag nodes over or close to certain other nodes. It does seem to settle after a bit. Not sure how to fix this, but should be ok for the most part.

Please try version 1.1.0 (Nuget is hasn't indexed the new version which may mean you have to wait a few hours)

- First uninstall the current version with 
`dotnet tool uninstall --global DependenSee`

- Install the latest 
`dotnet tool install --global DependenSee --version 1.1.0`

Please let me know if this resolves the issue 😊

And thanks for using DependenSee

**Comment by Piedone** [comment]
Wow, that was quick, thank you! Looks beautiful, this is the same project now without any manual intervention:
![image](https://user-images.githubusercontent.com/1976647/105840283-12052f80-5fd3-11eb-9e56-3aecaf89baf8.png)

A basic force-directed layout is fine, which I guess you're already using.
