### ISSUE TITLE
Access to output path is always forbidden

### ISSUE THREAD

**Issue by primepeter** [madushans/DependenSee#31]
If I use:  
`DependenSee "<Inputpath>" "<outputpath>" `
in PowerShell, I always get the following Error.

Error:
UnauthorizedAccessException:Access to the path 'D:\....' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)

I've tried everything.
with PowerShell with admin privileges:
different output paths
users\documents as output path
different input paths with different projects

I've even build the solution myself with manifest and requestedExecutionLevel level="requireAdministrator" 

It seems that i cant get DependenSee to get the privileges to create a file

**Comment by madushans** [comment]
This seems like an environment issue. can you provide the following please

- OS Version (try `winver`)
- dotnet version (try `dotnet --info`)
- DependenSee version (try `dotnet tool list -g`)
- full command line
- full output
- can you run DependenSee against an empty folder? Do you still get the same error?

**Comment by primepeter** [comment]
My bad, I have only specified an output folder and not an output filename.
If I specify an output filename, everything works fine.

**Comment by madushans** [comment]
oh cool. no worries. I'll keep this in mind to check and add a useful error message.
